version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment: 
      - SECRET_KEY=8b&08s^7-$$^n=jp5^w^v7%2h__kxr&s6rzh&-i-e4fn$$p9yxn)
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_ZFlmsNsWWlK2g8I5iFDm1PVL00EeFieWkK
      - STRIPE_TEST_SECRET_KEY=sk_test_eHtj3yxP8FeNTL8zdQpR7aPT00hUgtEZt4

    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes: 
  postgres_data: